### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Dichel** [ksu-hmi/Get-Well-Stay-Well#1]
- [x] Test Readmission Prevention repository 
- [x] Install Kivy to run code and report any issues
- [x] Document issues and how to improve the application.

**Comment by Dichel** [comment]
- [ ] Figure out how to install Kivy - having problems running code in python
- [ ] Try to figure out Kivy MD for updates user interfaces for a more modern looking app
